### ISSUE TITLE
Stop trying re-connect with unresponsive relays

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro#111]
Mostro is always trying to re-connect unresponsive relays, this is a waste of server resources and also we are generating a lot of useful log lines, I just got 600 MB on logs for only 4 days, we need to stop connecting again and again to unresponsive relays.

Not sure how to do it because I can see on logs that fully responsive relays also get disconnected and connected again, so we can't just stop connecting a relay after a disconnection, we can discuss here different ways of solve this problem.

**Comment by grunch** [comment]
I think nostr-sdk improvement is great for us, both of your suggestions sounds great, I am leaning towards the first option because API are not always reliable in terms of communication, I think the Mostro admin should be aware of what are the relays it should connect

**Comment by arkanoider** [comment]
I agree on the fact that API are  unreliable and admni should set his preferred relays.
I will work on scheduler to realize the time ban of unresponsive relays.
