### ISSUE TITLE
Feat request: set invoicing timer

### ISSUE THREAD

**Issue by alganza** [MostroP2P/mostro#196]
I've been testing Mostro a little and I find the 15 minutes timer to send the LN invoice as a buyer is too short.  I have failed to do it a bunch of times.  It would be great having more time or, even better, having the option to choose that time at order making time.

I use Robosats all the time and I love that you can chose both the public duration of your order (up to 24 hours) as well as the escrow/invoice timer (up to 8 hours).  I always set 24 and 8 hours respectively, what, together with their Telegram notifications, allows me to never miss when one of my orders gets taken, even when I fall asleep during the night (I always still have some time to do it in the morning).  A similar way to choose those times (at least to increase some the 15 minutes timer for the invoice) on Mostro would be very beneficial, IMO.

**Comment by grunch** [comment]
Hi @alganza thank you for your issue, this feature looks like a nice add, let's have this issue open and have it our backlog until we can code it or receive an external contribution

**Comment by grunch** [comment]
this was implemented on last versión

closing it via
https://github.com/MostroP2P/mostro/releases/tag/v0.11.3
