### ISSUE TITLE
When a dispute begins, Mostro shows those involved the solver's npub

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro#197]
When a dispute begins, the Solver who takes it must write a DM to those involved. The buyer and seller must wait for the Solver to contact them and in the meantime they do not know who will assist them (unless there is only 1 possible solver).

Since the buyer and seller do not know who will handle the dispute, it could happen that a malicious user who manages to learn that they are both in dispute could pose as a solver and write to them asking for personal information or money to "resolve" the dispute, or any other trick.

**Describe the solution you would like**
That Mostro shows the buyer and seller involved in a dispute the npub of the solver who will handle their dispute so that they can open DM to the solver, or so that they know who will assist them and can verify that the person writing to them is the real solver and not an imposter.

**Comment by grunch** [comment]
now when a solver takes a dispute Mostro send this message to both parties

```json
{
  "order": {
    "version": 1,
    "id": "aacfdbec-5bc0-43af-8767-06450730bb37",
    "pubkey": null,
    "action": "admin-took-dispute",
    "content": {
      "peer": {
        "pubkey": "dbe0b1be7aafd3cfba92d7463edbd4e33b2969f61bd554d37ac56f032e13355a"
      }
    }
  }
}
```
