### ISSUE TITLE
Validate NewOrder with buyer_invoice

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro#199]
When an new buy order have `buyer_invoice` with a botl11 LN invoice  we should validate: 

1. If amount = 0, the invoice MUST be amountless
2. If amount != 0, the invoice amount MUST be equal to the order amount or amountless

In all cases we allow users to enter a lightning address instead of a bolt11 invoice.

This validation should be added on actions `new-order` and `add-invoice`.

**Comment by arkanoider** [comment]
Now with #206 we have closed the case of LN address checking amout == 0, but we still have to check if order is created with Bolt Invoice that amount is != 0 right?

**Comment by grunch** [comment]
> Now with #206 we have closed the case of LN address checking amout == 0, but we still have to check if order is created with Bolt Invoice that amount is != 0 right?

yes, thank you for your amazing work as always

closing it via #206
