### ISSUE TITLE
Send message to buyer after the payment fails

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro#211]
Message should have a new action `payment-failed` and indicate the payment attempts left.

With this information clients could create a message like this:

`I tried to send you the sats but the payment of your invoice failed, I will try ${attempts} more times in ${pendingPaymentWindow} minutes window, please check your node/wallet is online`

**Comment by arkanoider** [comment]
This should be quite easy, sending a message from the scheduler.
