### ISSUE TITLE
Allow solvers also can take disputes

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro#219]
So far a mostro admin can add a solver, but a solver still can't take or resolve disputes

**Comment by arkanoider** [comment]
@grunch if you want I can fix this...

**Comment by grunch** [comment]
> @grunch if you want I can fix this...

please

**Comment by arkanoider** [comment]
Starting to fix with #233

**Comment by arkanoider** [comment]
> Starting to fix with #233

Can we consider this closed @grunch ?

**Comment by grunch** [comment]
> > Starting to fix with #233
> 
> Can we consider this closed @grunch ?

almost done 😃
