### ISSUE TITLE
correction in the invoice update message

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro#221]
If an invoice has already been paid and the buyer tries to update it anyway, this message appears:

```
Mostro sent you this message for order id: 50fdd1b3-9e5f-4eb9-b763-6cee64af3d0b at 12:45 date - 22/03/2024

Order Id 50fdd1b3-9e5f-4eb9-b763-6cee64af3d0b status must be WaitingBuyerInvoice!

Bye Bye!
```
But it was already PurchaseCompleted. It should say that the invoice has already been paid, not that status must be WaitingBuyerInvoice

**Comment by arkanoider** [comment]
Hi @Catrya ,

clear, we use the same string for all the other states and maybe we can meke it more generic changing to:
 
...you can't add an invoice to an order with status x

What do you say?

**Comment by Catrya** [comment]
hey @arkanoider 
sure, agree, much better that way

**Comment by arkanoider** [comment]
Will fix!

**Comment by arkanoider** [comment]
Closing this with #223
