### ISSUE TITLE
Do not allow an admin/solver settle or cancel an order if it is not in dispute

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro#232]
Currently Mostro allows an admin to use `admcancel` and `admsettle` regardless of the status of an order. That can have some issues:

1) If the buyer has not yet put the invoice to receive the sats, but the admin puts admsettle (it doesn't make much sense to do it but it can happen) Mostro will stop: 

![Captura desde 2024-03-26 16-33-18](https://github.com/MostroP2P/mostro/assets/140891948/1c350c0f-1f78-4135-b87a-c36714519d6c)

but i tested it again and the error was diferent:
![Captura desde 2024-03-27 09-51-13](https://github.com/MostroP2P/mostro/assets/140891948/f58159bd-6e0f-4641-b1c7-565656fabf83)

2) If an administrator of any Mostro were malicious, they could cancel or settle orders as they wanted.

**Solution i´d like**

That an admin/solver can only put `admcancel` or `admsettle` if they have taken a dispute previously (with `admtakedispute`). And if mostro also tells users which admin took it, the better (https://github.com/MostroP2P/mostro/issues/197)

**Comment by grunch** [comment]
fixed on 0dabc1045720f8ca89c6e34440ec135d0b04c809
