### ISSUE TITLE
dispute's status is being saved on database on camel case

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro#235]
When a dispute is created the status is saved in camel case, but it should be saved on kebab case.

**Comment by arkanoider** [comment]
Hi @grunch ,

my 2 cents on this...just speakin loud...could be this?

https://github.com/MostroP2P/mostro-core/blob/b1352c064b06c8230cd93267c494839bfda922c7/src/dispute.rs#L59

I think we should use a String type for status in dispute struct and then .to_string() the status before saving it.

**Comment by grunch** [comment]
> Hi @grunch ,
> 
> my 2 cents on this...just speakin loud...could be this?
> 
> https://github.com/MostroP2P/mostro-core/blob/b1352c064b06c8230cd93267c494839bfda922c7/src/dispute.rs#L59
> 
> I think we should use a String type for status in dispute struct and then .to_string() the status before saving it.
> 
> 

why is better idea to use a string type instead an enum like in order?

**Comment by arkanoider** [comment]
> > Hi @grunch ,
> > my 2 cents on this...just speakin loud...could be this?
> > https://github.com/MostroP2P/mostro-core/blob/b1352c064b06c8230cd93267c494839bfda922c7/src/dispute.rs#L59
> > I think we should use a String type for status in dispute struct and then .to_string() the status before saving it.
> 
> why is better idea to use a string type instead an enum like in order?

Not a better idea absolutely, I just watched that in order struct ( where crud crate seems working right ) we have status set as a string:

https://github.com/MostroP2P/mostro-core/blob/b1352c064b06c8230cd93267c494839bfda922c7/src/order.rs#L117

In the migration it's a varchar both on dispute and orders...

I think that something in the magic of the code is not converting explicitly to string in this case...just a supposition anyway.

If i can i will try...

**Comment by arkanoider** [comment]
Yup!

![immagine](https://github.com/MostroP2P/mostro/assets/113362043/56b701a6-6492-4c0f-bf7a-6c4a15ab77d2)

first one with status second one with string

**Comment by grunch** [comment]
thanks for this fix @arkanoider

closing it via #237
