### ISSUE TITLE
New nip33 event to publish mostro useful data

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro#257]
We need to publish a scheduled event that gives useful Mostro's information to users, I'm thinking something like this:

```json
[
  "EVENT",
  "RAND",
  {
    "id": "84fad0d29cb3529d789faeff2033e88fe157a48e071c6a5d1619928289420e31",
    "pubkey": "dbe0b1be7aafd3cfba92d7463edbd4e33b2969f61bd554d37ac56f032e13355a",
    "created_at": 1702548701,
    "kind": 38383,
    "tags": [
      ["d", "dbe0b1be7aafd3cfba92d7463edbd4e33b2969f61bd554d37ac56f032e13355a"],
      ["mostro_fee", "0.006"],
      ["max_routing_fee", "0.002"],
      ["max_order_amount", "1000000"],
      ["expiration_hours", "24"],
      ["max_expiration_days", "15"],
      ["relays", [
         "ws://localhost:7000",
         "ws://localhost:8000",
      ]],
      ["version", "0.11.5"],
      ["commit", "09e9862a7f572f73483935166d515d84863b84d6"],
      ["ln_node", "031df9367377758ef6a167f218023c5a1dcf3994d3e96327d32f0f008548fe4236@g4zneovmezzbtsrqux3ayfafllmj3qc5cdhm6nvxkyqhk7cevk2ofpid.onion:9735"]
      ["y", "mostrop2p"],
      ["z", "settings"]
    ],
    "content": "",
    "sig": "7e8fe1eb644f33ff51d8805c02a0e1a6d034e6234eac50ef7a7e0dac68a0414f7910366204fa8217086f90eddaa37ded71e61f736d1838e37c0b73f6a16c4af2"
  }
]
```

**Comment by tincho70** [comment]
First at all, I've a question: why `tags` and not `content`?
Then, maybe add additional information with statistics about trades (number of succefull last 1, 15 and 30 days)

**Comment by Catrya** [comment]
I also think it's good to add: mostro's uptime, the average time in which the solvers take the disputes, Mostro rate (when implemented)

**Comment by grunch** [comment]
> First at all, I've a question: why `tags` and not `content`? Then, maybe add additional information with statistics about trades (number of succefull last 1, 15 and 30 days)

tags are easy to read, they can be extracted from the event easier because there is a nip about tags.

we are trying to implement the stats on this PR https://github.com/MostroP2P/mostro/pull/251 but it's not ready yet, I just created an issue here #265 to try to organize better our ideas, please go there for stats related suggestions

**Comment by bilthon** [comment]
The `expiration_seconds` is another configuration parameter that would be nice to include here. Right now the web client has this visual countdown, but it's value is hard-coded to 15 minutes. It would be nice to be able to extract this data from the NIP-33 event.

Also regarding the relay list, I think [NIP-65](https://github.com/nostr-protocol/nips/blob/master/65.md) specifies kind `10002` precisely for this purpose. So it might be better to put relay data there.

**Comment by arkanoider** [comment]
A first implementation of mostro settings is presented in #279 .

Waiting for review.

**Comment by grunch** [comment]
closing it via #279
