### ISSUE TITLE
Admin has to take a dispute to resolve it

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro#263]
I think that an admin/solver should only be able to cancel or resolve a dispute order if they take the dispute (it is not enough that an order it is in dispute status, but also that the administrator is responsible for that dispute)

Currently, an admin can decide on an order simply if it is in status: dispute (they doesn't even have to accept it) in that case the seller and the buyer will not know who resolved their dispute (because the admin never accepted it). That can be confusing for users.

Maybe not a priority, but it could improve behavior a little more

**Comment by grunch** [comment]
We can't put in the same group admins and solvers, I think this is ok with solvers but not with THE admin, the admin is the node operator, so it should be able of settle and cancel order when it find it necessary, for example, if there is a bug and the order is stuck only an admin with `super powers` can solve the problem
