### ISSUE TITLE
re-subscribe hold invoices after start

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro#266]
If mostrod is restarted it lost connection with lightning node, so it will lost the hold invoice subscription, as a consecuence when a seller send the payment mostrod is not able to know who paid, to fix this we need to resuscribe invoices after start

[Here](https://github.com/lnp2pBot/bot/issues/132) how we implemented it on [@lnp2pbot](https://github.com/lnp2pBot/bot)

**Comment by arkanoider** [comment]
Going on this from the next week!

**Comment by arkanoider** [comment]
First step...

https://github.com/MostroP2P/mostro/pull/330
