### ISSUE TITLE
add the option for users to see all their current orders

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro#275]
If a user has several orders in different statuses, it is likely that they will forget some or find it difficult to remember them all.
I suggest adding the option so that users can see a list of all the orders they have that are not in status: canceled, success, canceled-by-admin or settled-by-admin

**Comment by arkanoider** [comment]
Hi @Catrya ,

I think this could me more related to web mostro or to CLI. @grunch what do you think?

**Comment by Catrya** [comment]
Yes you're right. I'm going to put it in the other 2 repos and remove it from this one :)
