### ISSUE TITLE
if it is a range order do not allow creating an order with the amount of sats 

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro#288]
Currently, when you are going to make an order by range you can type:
```
mcli neworder -k sell -f 50-70 -a 200 -c cup -m test 
```
and it will be published without a problem.

If you are going to create an order by ranges, mostro should not allow you to also put the amount in sats because it does not make sense.

**Comment by arkanoider** [comment]
Good job!

What's the correct reaction @Catrya ? If enter is pressed I can immedeately give an error message to user and avoid also sending out to mostro anything? 
What do you think?

cc @grunch @bilthon

**Comment by grunch** [comment]
> Good job!
> 
> What's the correct reaction @Catrya ? If enter is pressed I can immedeately give an error message to user and avoid also sending out to mostro anything? What do you think?
> 
> cc @grunch @bilthon

Just another validation on mostrod, if is a range order and the `amount` is set, just send a error message to user and leave the function

**Comment by arkanoider** [comment]
Will fix this later today, I think this is to fix in CLI right @grunch ?

> Currently, when you are going to make an order by range you can type:
> 
> ```
> mcli neworder -k sell -f 50-70 -a 200 -c cup -m test 
> ```
> 
> and it will be published without a problem.
> 
> If you are going to create an order by ranges, mostro should not allow you to also put the amount in sats because it does not make sense.

**Comment by arkanoider** [comment]
> > Good job!
> > What's the correct reaction @Catrya ? If enter is pressed I can immedeately give an error message to user and avoid also sending out to mostro anything? What do you think?
> > cc @grunch @bilthon
> 
> Just another validation on mostrod, if is a range order and the `amount` is set, just send a error message to user and leave the function

This is preferrable @grunch in your opinion? We centralize in mostrod discard of this message to avoid to all client to filter this kind of message?

**Comment by grunch** [comment]
> > > Good job!
> > > What's the correct reaction @Catrya ? If enter is pressed I can immedeately give an error message to user and avoid also sending out to mostro anything? What do you think?
> > > cc @grunch @bilthon
> > 
> > 
> > Just another validation on mostrod, if is a range order and the `amount` is set, just send a error message to user and leave the function
> 
> This is preferrable @grunch in your opinion? We centralize in mostrod discard of this message to avoid to all client to filter this kind of message?

mostrod must validate in order to be stable and secure, clients could validate in order to bring a better UX to users
