### ISSUE TITLE
Add kind 38383 to NIPs

### ISSUE THREAD

**Issue by AsaiToshiya** [MostroP2P/mostro#299]
Does Mostro have the possibility to connect to global relays? If so, please consider adding kind 38383 to [NIPs](https://github.com/nostr-protocol/nips) to avoid future confusion.

**Comment by grunch** [comment]
yes of course we need to work on a NIP.

In fact as Mostro, [@lnp2pbot](https://github.com/lnp2pBot/bot) is also publishing new orders as kind 38383 events on nostr, both are following the same [standard](https://mostro.network/messages/) and the main idea is that all p2p plaforms publish events on nostr and having all those orders on nostr to have an easy way of find what you are looking for.

**Comment by AsaiToshiya** [comment]
Thanks for your reply. You are understanding, so no problem. I'll close this issue.
