### ISSUE TITLE
Panic error when an admin tries to settle a canceled order

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro#303]
If buyer and seller open a dispute, but before solver resolves it they do a cooperative cancellation, if solver tries to do Settle, it will cause panic error and Mostro stops. Mostro should tell the solver that the order has already been cancelled and not try to pay the invoice.

![Captura desde 2024-06-20 21-41-17](https://github.com/MostroP2P/mostro/assets/140891948/7430a81b-e8b4-4dc5-b886-5865efd81ff3)

**Comment by arkanoider** [comment]
Preparing a hotfix to avoid panic.
