### ISSUE TITLE
Replace all text strings sent to users with actions

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro#312]
If we send english text strings from mostrod to clients, multilingual clients will have to match those exact english text strings to translate it to users languages, that would be an ugly fix, instead we should use descriptive actions that with-in the context clients devs could easily show the text string in the correct language to the user.

New actions should be added to [mostro-core](https://github.com/MostroP2P/mostro-core) library

**Comment by f3r10** [comment]
Hello, could I take this issue?

**Comment by grunch** [comment]
> Hello, could I take this issue?

hi @f3r10 thanks for offer your contribution, but I think @Catrya is already working on this issue, but you can take another one you like 😃

**Comment by Catrya** [comment]
Closed via #340
