### ISSUE TITLE
[NIP-65] Publish list of relays

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro#318]
In order to be sure that events between mostrod and clients are being read by each part, we can follow [NIP-65](https://github.com/nostr-protocol/nips/blob/master/65.md) to make mostrod publish an event with a list of relays that mostrod is using, so clients can use the same relays, this is a replaceable event and must be published by the scheduler in a time window, **in seconds**, to complete this issue we need to add a new variable on  `[mostro]` section on the `settings.toml` file, the variable could be named `publish_relays_interval`, the relay list must be taken from the variable `relays` inside `[nostr]` section.

**Comment by arkanoider** [comment]
closed with #319
