### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cymqqqq** [MostroP2P/mostro#339]
About this:
sequenceDiagram
    autonumber
    Seller->>Mostro: I want to sell Bitcoin
    Mostro-->>LN-Node: Give me a hold invoice
    LN-Node->>Mostro: Hold invoice
    Mostro->>Seller: Please pay this hold invoice
    Seller->>LN-Node: Paying through lightning
    LN-Node-->>Mostro: Payment received
    Mostro-->>Seller: Thanks! talk to buyer now
I'm a little bit confused about why we can not perform p2p communication directly with LN-node, but build on top of the nostr protocol.

**Comment by Catrya** [comment]
> I'm a little bit confused about why we can not perform p2p communication directly with LN-node, but build on top of the nostr protocol.
Hi, what does it mean? Can you explain more?
