### ISSUE TITLE
Add a request id field in messages

### ISSUE THREAD

**Issue by arkanoider** [MostroP2P/mostro#377]
Hi @grunch @bilthon ,

as requested from @bilthon as enhancement for clients I have added a very simple `request_id` in messages that will echo the received one from client messages.
I understood that this thing is useful for clients so I want to refactor code with a more clear implementation.

Now I extract from incoming message the field and propagate it in all actions, but in some cases i put an option in the field, for example if there is a `resubscribe action` of an invoice at mostro startup i cannot add it because i did not receive a message from the client, the are some other cases like that, typically in invoices management.
Now I ask you if we need this  new field also in these case? @bilthon drop me your ideas of the messages where the echo is needed.

I have in mind two ways to improve this:

- Add an `atomic` static variable, so I can use it everywhere easily, but still usable no for all messages.
- Add a db field so we can still have this number available.

Drop me your ideas here...

**Comment by arkanoider** [comment]
Closed via #376

**Comment by arkanoider** [comment]
Closed via #376

**Comment by grunch** [comment]
closing it via #376
