### ISSUE TITLE
Add reputation system

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro#42]
We need to add a reputation system like the one we use in [@lnp2pbot](https://github.com/lnp2pBot/bot/blob/main/bot/commands.js#L279) but for this we should save user's reputation as a nip33 event on Nostr. Any time users can query other users reputation.

We should be able to send this fields on the event published
```
total_reviews: integer
total_rating: integer
last_rating: integer
min_rate: integer
max_rate: integer
```
The new reputation should be a new index from 1 to 5, calculated using the successful trades and volume in sats.

We can do it the same way we are posting orders, I mean serializing it on `content` field, and to calculate we should use the same logic on the lnp2pbot link above.

**Comment by arkanoider** [comment]
Hi @grunch , 

just to share my idea on reputation and to see other guys ideas, also because Nostr and Nip 33 could have some differences from a classic approach.

One thing that I was thinking about is that a user could have different reputation on different mostro instance, this because in my mind it will be mostro to send the update of NIP33 reputation event to relay, and I think there's nothing bad in this, but I wanted to share my idea before I am missing something. Let me know your opinion about.

Going on, I think ( at the moment ) that we can imagine two scenarios:

- Users can ask reputation on another user **anytime**, so a command like _Reputation_Request_ is needed.
- Users ( Buyer and Seller ) can give a vote ( 1- 5 like the bot ) after a **succesful** trade.

For the first kind of command, I suppose something like this:

```mermaid
sequenceDiagram
    autonumber
    participant User
    participant Mostro
    User->>Mostro: Ask for user reputation with NIP4 command
    Mostro->>Mostro: Request user reputation from relays <br/> ( NIP 33 event )
    Mostro->>User: Send back as direct message ( NIP 4 ) info to user
```
For the other scenario, where a successful trade is made, we have a situation like this:

```mermaid
sequenceDiagram
    autonumber
    participant Buyer
    participant Mostro
    participant Seller
    
    Seller->>Mostro: Create Sell offers
    Mostro->>Mostro: Publish offer as Nostr event
    Buyer->>Mostro: Take the Sell offer
    Mostro->>Mostro: Wait for order to complete
    par Mostro to Buyer
        Mostro->>Buyer: Order successful! Please vote Seller.
    and Mostro to Seller
        Mostro->>Seller: Order successful! Please vote Buyer.
    end
    Buyer->>Mostro: Send vote for the Seller ( 1 -5 )
    Seller->>Mostro: Send vote for the Buyer ( 1 -5 )
    Mostro->>Mostro: Send to relays the votes of the counterpart <br/> updating their NIP33 with d tag with NPub value
```
For the NIP33 update I think that we should mark the order as voted by Buyer/Seller, otherwise a _smart user_ could send many vote for the same order. Am i right?

This is basically what is in my mind at the moment.

The next cool thing could be, as we said in the chat, to add to the _Reputation_Request_ command other infos so that the user can evaluate the reliability of the counterpart, for example:

- Followers
- Badges
- Volume of exchange
- ...

Here my two cents! Let me know...

**Comment by grunch** [comment]
Your second diagram is ok, mostro request users to vote and then broadcast the nip33 evento with d tag =userpubkey and the content is a json serialized with the current rating user values

Your first diagram is not right, users don't need to ask to Mostro about user reputation because the reputation is already on nostr relays, clients just need to make a regular nostr request to relays asking for a specific pubkey, reputation is totally public

and yes, users will have different reputation on different Mostros, we should think in some kinda unification.. or not 🤷🏾‍♂️

**Comment by arkanoider** [comment]
You're right! It's just an event...will start workin on this

**Comment by nobu-maeda** [comment]
> Your second diagram is ok, mostro request users to vote and then broadcast the nip33 evento with d tag =userpubkey and the content is a json serialized with the current rating user values
> 
> Your first diagram is not right, users don't need to ask to Mostro about user reputation because the reputation is already on nostr relays, clients just need to make a regular nostr request to relays asking for a specific pubkey, reputation is totally public
> 
> and yes, users will have different reputation on different Mostros, we should think in some kinda unification.. or not 🤷🏾‍♂️

From n3xB here. Different rep on diff Mostro is a problem. Just having user reputation limited to Mostro is also a problem. If we want user to own their rep and can transport from platform to platform, then a more generalized open and well defined protocol is needed to invite other developers to build inter-compatible ecosystem.

More concrete proposal both in terms of standardization, and suggestion for Mostro, coming soon.

**Comment by nobu-maeda** [comment]
And before I can complete the concrete proposal, there's also some prior art here. Namely Bisq, and this discussion on RoboSats
https://github.com/Reckless-Satoshi/robosats/issues/39

**Comment by arkanoider** [comment]
Hi @nobu-maeda ,

thanks for the interesting thread first of all. I am not an expert in cryptography nor in privacy models. I am an embedded dev with a passion for bitcoin ( and crypto ).
I admit that this is really a simple model for reputation and all the ideas the improve privacy are welcome, but the real dispute is having it or not having it?
I admit that I that I like the approach of robosats with the bond, a reputation can have anyway point of attack in the end, but I am not an expert and I see many people citing Chaumian models to improve and distribute it, but I am not an expert and need to study about.

Maybe the only way to get trust is putting some btc in a sort of bond, but for sure is not a solution.

I see a sort of dog eating his tail in the end, from one side we want infinite and "anymous" identities, but on the other side we want to evaluate all that identities. A trade off is needed imo.

Anyway i'm lookin forward to read your proposal, this first easty approach is the porting of the one used by @grunch in [lnp2p](https://lnp2pbot.com/).

My two cents...

Let's work and make this Mostro a beauty guys!

**Comment by grunch** [comment]
About reputation system there is no right answer, different models can have positive results, we are basing this implementation on the one that we built almost 2 years ago and is working pretty well but of course there is always room to improve it, I'll wait to read your proposal @nobu-maeda the privacy on Mostro is something we are working to address, take a look on this [discussion](https://github.com/MostroP2P/mostro/discussions/56) where we are using ephemeral identities to avoid a third party link operations to track user's movements.

Clients can also create ephemeral identities of ephemeral identities, with Mostro clients have a lot of freedom, we still don't know exactly how will be used the final product because users tend to point the way.
