### ISSUE TITLE
In FLOW.md. Lightning invoice created by Buyer/Taker is same as one by Mostro to Seller/Maker

### ISSUE THREAD

**Issue by nobu-maeda** [MostroP2P/mostro#52]
In [FLOW.md](https://github.com/MostroP2P/mostro/blob/main/FLOW.md), it seems that the Lightning invoice created by Buyer/Taker is same as one by Mostro to Seller/Maker. Is this intentional and some sort of Lightning invoice mechanics that I'm not aware of (perhaps how HODL invoice works?). But not clear to me how so. Flagging to see if this is intentional.

**Comment by grunch** [comment]
that LN invoice is just an example, it could be replaced by `lnbc1...`
